name: Publish

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v5
      - run: uv sync --locked --all-extras --dev
      - run: uv build
      - run: uv publish -t ${{ secrets.PYPI_TOKEN }}
